services:
  wildintel-tools:
    image: ghcr.io/ijfvianauhu/trapper-client:latest
    container_name: trapper-client
    restart: unless-stopped
    volumes:
      # Internal volume for settings persistence
      - trapper_client_settings:/home/trapper/.config/trapper-client
      # Mount for data directory (user-defined)
      - ${DATA_PATH:-./data}:/data
    # user: "1000:1000"
    env_file:
      - .env
    stdin_open: true
    tty: true

volumes:
  trapper_client_settings:  # Named volume for settings persistence
